### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by JusticeByLu** [Riadh-Bouarroudj/Reversible-fragile-watermarking#1]
Hello, author! I would like to ask what the title of the paper for this project is. I want to understand it in conjunction with the paper.

**Comment by Riadh-Bouarroudj** [comment]
Hello JusticeByLu,

Unfortunately, the conference paper associated with this code is not available online yet. However, you can find further explanations in the two papers below regarding the overall pipeline of watermarking techniques, the reversible process, some sections on the embedding and extraction techniques. Etc. 
Even though these papers present different works, some parts of the methodology are similar to this project.

- Riadh Bouarroudj et al. "A reversible fragile watermarking technique using fourier transform and Fibonacci Q-matrix for medical image authentication", Biomedical Signal Processing and Control,  https://doi.org/10.1016/j.bspc.2024.105967

- R. Bouarroudj et al. "Reversible Fragile Watermarking for Medical Image Authentication in the Frequency Domain" https://doi.org/10.1109/IC2EM59347.2023.10419699

**Comment by JusticeByLu** [comment]
Thank you very much
